package com.jing.emperor.domain.model;

import java.util.Date;

public class EmpUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.id
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.gmt_create
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private Date gmtCreate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.gmt_modified
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private Date gmtModified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.creator
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.modifier
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private String modifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.is_deleted
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private String isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.mobile_num
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private String mobileNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.user_name
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.sex
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.id_card
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private String idCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.birth_day
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private Date birthDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.password
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.login_id
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private String loginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.photo_url
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private String photoUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_user.org_id
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	private String orgId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.id
	 * @return  the value of emp_user.id
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.id
	 * @param id  the value for emp_user.id
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.gmt_create
	 * @return  the value of emp_user.gmt_create
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.gmt_create
	 * @param gmtCreate  the value for emp_user.gmt_create
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.gmt_modified
	 * @return  the value of emp_user.gmt_modified
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.gmt_modified
	 * @param gmtModified  the value for emp_user.gmt_modified
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.creator
	 * @return  the value of emp_user.creator
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.creator
	 * @param creator  the value for emp_user.creator
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.modifier
	 * @return  the value of emp_user.modifier
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public String getModifier() {
		return modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.modifier
	 * @param modifier  the value for emp_user.modifier
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.is_deleted
	 * @return  the value of emp_user.is_deleted
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public String getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.is_deleted
	 * @param isDeleted  the value for emp_user.is_deleted
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.mobile_num
	 * @return  the value of emp_user.mobile_num
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public String getMobileNum() {
		return mobileNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.mobile_num
	 * @param mobileNum  the value for emp_user.mobile_num
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setMobileNum(String mobileNum) {
		this.mobileNum = mobileNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.user_name
	 * @return  the value of emp_user.user_name
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.user_name
	 * @param userName  the value for emp_user.user_name
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.sex
	 * @return  the value of emp_user.sex
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.sex
	 * @param sex  the value for emp_user.sex
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.id_card
	 * @return  the value of emp_user.id_card
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public String getIdCard() {
		return idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.id_card
	 * @param idCard  the value for emp_user.id_card
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.birth_day
	 * @return  the value of emp_user.birth_day
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public Date getBirthDay() {
		return birthDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.birth_day
	 * @param birthDay  the value for emp_user.birth_day
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setBirthDay(Date birthDay) {
		this.birthDay = birthDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.password
	 * @return  the value of emp_user.password
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.password
	 * @param password  the value for emp_user.password
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.login_id
	 * @return  the value of emp_user.login_id
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public String getLoginId() {
		return loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.login_id
	 * @param loginId  the value for emp_user.login_id
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.photo_url
	 * @return  the value of emp_user.photo_url
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public String getPhotoUrl() {
		return photoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.photo_url
	 * @param photoUrl  the value for emp_user.photo_url
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_user.org_id
	 * @return  the value of emp_user.org_id
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_user.org_id
	 * @param orgId  the value for emp_user.org_id
	 * @mbg.generated  Sat May 06 16:11:40 CST 2017
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}
}