package com.jing.emperor.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.jing.emperor.domain.model.Person;
import com.jing.emperor.domain.model.PersonExample;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);
}