package com.jing.emperor.domain.model;

import java.util.Date;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;


public class EmpOrg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_org.id
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_org.gmt_create
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	@NotNull(message = "创建日期不能为空")
	private Date gmtCreate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_org.gmt_modified
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	@NotNull(message = "修改日期不能为空")
	private Date gmtModified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_org.creator
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	@NotEmpty(message = "创建人不能为空")
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_org.modifier
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	@NotEmpty(message = "修改人不能为空")
	private String modifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_org.is_deleted
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	@NotEmpty(message = "是否删除不能为空")
	private String isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_org.name
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	@NotEmpty(message = "区域名称不能为空")
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_org.parent_id
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	@NotNull(message = "父节点不能为空")
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_org.remark
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_org.id
	 * @return  the value of emp_org.id
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_org.id
	 * @param id  the value for emp_org.id
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_org.gmt_create
	 * @return  the value of emp_org.gmt_create
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_org.gmt_create
	 * @param gmtCreate  the value for emp_org.gmt_create
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_org.gmt_modified
	 * @return  the value of emp_org.gmt_modified
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_org.gmt_modified
	 * @param gmtModified  the value for emp_org.gmt_modified
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_org.creator
	 * @return  the value of emp_org.creator
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_org.creator
	 * @param creator  the value for emp_org.creator
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_org.modifier
	 * @return  the value of emp_org.modifier
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public String getModifier() {
		return modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_org.modifier
	 * @param modifier  the value for emp_org.modifier
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_org.is_deleted
	 * @return  the value of emp_org.is_deleted
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public String getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_org.is_deleted
	 * @param isDeleted  the value for emp_org.is_deleted
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_org.name
	 * @return  the value of emp_org.name
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_org.name
	 * @param name  the value for emp_org.name
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_org.parent_id
	 * @return  the value of emp_org.parent_id
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_org.parent_id
	 * @param parentId  the value for emp_org.parent_id
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_org.remark
	 * @return  the value of emp_org.remark
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_org.remark
	 * @param remark  the value for emp_org.remark
	 * @mbg.generated  Mon May 01 17:10:37 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}