package com.jing.emperor.domain.model;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.id
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.last_name
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.first_name
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.address
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persons.city
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.id
     *
     * @return the value of persons.id
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.id
     *
     * @param id the value for persons.id
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.last_name
     *
     * @return the value of persons.last_name
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.last_name
     *
     * @param lastName the value for persons.last_name
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.first_name
     *
     * @return the value of persons.first_name
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.first_name
     *
     * @param firstName the value for persons.first_name
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.address
     *
     * @return the value of persons.address
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.address
     *
     * @param address the value for persons.address
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persons.city
     *
     * @return the value of persons.city
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persons.city
     *
     * @param city the value for persons.city
     *
     * @mbg.generated Sun Apr 30 20:53:12 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }
}