package com.jing.emperor.domain.model;

import java.util.Date;

public class EmpCar {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.id
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.gmt_create
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private Date gmtCreate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.gmt_modified
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private Date gmtModified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.creator
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.modifier
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private String modifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.is_deleted
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private String isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.car_no
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private String carNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.car_brand
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private String carBrand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.car_seats
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private Integer carSeats;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.car_type
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private String carType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.car_insurance_info
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private String carInsuranceInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.car_buy_date
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private Date carBuyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car.org_id
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	private String orgId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.id
	 * @return  the value of emp_car.id
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.id
	 * @param id  the value for emp_car.id
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.gmt_create
	 * @return  the value of emp_car.gmt_create
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.gmt_create
	 * @param gmtCreate  the value for emp_car.gmt_create
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.gmt_modified
	 * @return  the value of emp_car.gmt_modified
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.gmt_modified
	 * @param gmtModified  the value for emp_car.gmt_modified
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.creator
	 * @return  the value of emp_car.creator
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.creator
	 * @param creator  the value for emp_car.creator
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.modifier
	 * @return  the value of emp_car.modifier
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public String getModifier() {
		return modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.modifier
	 * @param modifier  the value for emp_car.modifier
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.is_deleted
	 * @return  the value of emp_car.is_deleted
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public String getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.is_deleted
	 * @param isDeleted  the value for emp_car.is_deleted
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.car_no
	 * @return  the value of emp_car.car_no
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public String getCarNo() {
		return carNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.car_no
	 * @param carNo  the value for emp_car.car_no
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setCarNo(String carNo) {
		this.carNo = carNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.car_brand
	 * @return  the value of emp_car.car_brand
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public String getCarBrand() {
		return carBrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.car_brand
	 * @param carBrand  the value for emp_car.car_brand
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setCarBrand(String carBrand) {
		this.carBrand = carBrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.car_seats
	 * @return  the value of emp_car.car_seats
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public Integer getCarSeats() {
		return carSeats;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.car_seats
	 * @param carSeats  the value for emp_car.car_seats
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setCarSeats(Integer carSeats) {
		this.carSeats = carSeats;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.car_type
	 * @return  the value of emp_car.car_type
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public String getCarType() {
		return carType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.car_type
	 * @param carType  the value for emp_car.car_type
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setCarType(String carType) {
		this.carType = carType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.car_insurance_info
	 * @return  the value of emp_car.car_insurance_info
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public String getCarInsuranceInfo() {
		return carInsuranceInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.car_insurance_info
	 * @param carInsuranceInfo  the value for emp_car.car_insurance_info
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setCarInsuranceInfo(String carInsuranceInfo) {
		this.carInsuranceInfo = carInsuranceInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.car_buy_date
	 * @return  the value of emp_car.car_buy_date
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public Date getCarBuyDate() {
		return carBuyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.car_buy_date
	 * @param carBuyDate  the value for emp_car.car_buy_date
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setCarBuyDate(Date carBuyDate) {
		this.carBuyDate = carBuyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car.org_id
	 * @return  the value of emp_car.org_id
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car.org_id
	 * @param orgId  the value for emp_car.org_id
	 * @mbg.generated  Mon May 01 17:09:28 CST 2017
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}
}