package com.jing.emperor.domain.model;

import java.util.Date;

public class EmpCarOrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order_detail.id
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order_detail.gmt_create
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order_detail.gmt_modified
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order_detail.creator
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order_detail.modifier
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order_detail.is_deleted
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    private String isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order_detail.customer_id
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order_detail.status
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order_detail.type
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order_detail.price
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order_detail.travel_id
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    private String travelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order_detail.order_id
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    private String orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order_detail.id
     *
     * @return the value of emp_car_order_detail.id
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order_detail.id
     *
     * @param id the value for emp_car_order_detail.id
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order_detail.gmt_create
     *
     * @return the value of emp_car_order_detail.gmt_create
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order_detail.gmt_create
     *
     * @param gmtCreate the value for emp_car_order_detail.gmt_create
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order_detail.gmt_modified
     *
     * @return the value of emp_car_order_detail.gmt_modified
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order_detail.gmt_modified
     *
     * @param gmtModified the value for emp_car_order_detail.gmt_modified
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order_detail.creator
     *
     * @return the value of emp_car_order_detail.creator
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order_detail.creator
     *
     * @param creator the value for emp_car_order_detail.creator
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order_detail.modifier
     *
     * @return the value of emp_car_order_detail.modifier
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order_detail.modifier
     *
     * @param modifier the value for emp_car_order_detail.modifier
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order_detail.is_deleted
     *
     * @return the value of emp_car_order_detail.is_deleted
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order_detail.is_deleted
     *
     * @param isDeleted the value for emp_car_order_detail.is_deleted
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order_detail.customer_id
     *
     * @return the value of emp_car_order_detail.customer_id
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order_detail.customer_id
     *
     * @param customerId the value for emp_car_order_detail.customer_id
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order_detail.status
     *
     * @return the value of emp_car_order_detail.status
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order_detail.status
     *
     * @param status the value for emp_car_order_detail.status
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order_detail.type
     *
     * @return the value of emp_car_order_detail.type
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order_detail.type
     *
     * @param type the value for emp_car_order_detail.type
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order_detail.price
     *
     * @return the value of emp_car_order_detail.price
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order_detail.price
     *
     * @param price the value for emp_car_order_detail.price
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order_detail.travel_id
     *
     * @return the value of emp_car_order_detail.travel_id
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public String getTravelId() {
        return travelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order_detail.travel_id
     *
     * @param travelId the value for emp_car_order_detail.travel_id
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public void setTravelId(String travelId) {
        this.travelId = travelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order_detail.order_id
     *
     * @return the value of emp_car_order_detail.order_id
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order_detail.order_id
     *
     * @param orderId the value for emp_car_order_detail.order_id
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
}