package com.jing.emperor.domain.model;

import java.util.Date;

public class EmpCarUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_user.id
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_user.gmt_create
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	private Date gmtCreate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_user.gmt_modified
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	private Date gmtModified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_user.creator
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_user.modifier
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	private String modifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_user.is_deleted
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	private String isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_user.car_no
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	private String carNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_user.user_id
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	private String userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_user.id
	 * @return  the value of emp_car_user.id
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_user.id
	 * @param id  the value for emp_car_user.id
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_user.gmt_create
	 * @return  the value of emp_car_user.gmt_create
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_user.gmt_create
	 * @param gmtCreate  the value for emp_car_user.gmt_create
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_user.gmt_modified
	 * @return  the value of emp_car_user.gmt_modified
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_user.gmt_modified
	 * @param gmtModified  the value for emp_car_user.gmt_modified
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_user.creator
	 * @return  the value of emp_car_user.creator
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_user.creator
	 * @param creator  the value for emp_car_user.creator
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_user.modifier
	 * @return  the value of emp_car_user.modifier
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public String getModifier() {
		return modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_user.modifier
	 * @param modifier  the value for emp_car_user.modifier
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_user.is_deleted
	 * @return  the value of emp_car_user.is_deleted
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public String getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_user.is_deleted
	 * @param isDeleted  the value for emp_car_user.is_deleted
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_user.car_no
	 * @return  the value of emp_car_user.car_no
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public String getCarNo() {
		return carNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_user.car_no
	 * @param carNo  the value for emp_car_user.car_no
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public void setCarNo(String carNo) {
		this.carNo = carNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_user.user_id
	 * @return  the value of emp_car_user.user_id
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_user.user_id
	 * @param userId  the value for emp_car_user.user_id
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}
}