package com.jing.emperor.domain.model;

import java.util.Date;

public class EmpCarSiteTravel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_site_travel.id
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_site_travel.gmt_create
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	private Date gmtCreate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_site_travel.gmt_modified
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	private Date gmtModified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_site_travel.creator
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_site_travel.modifier
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	private String modifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_site_travel.is_deleted
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	private String isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_site_travel.start_point
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	private String startPoint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_site_travel.end_point
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	private String endPoint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_site_travel.org_id
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	private String orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column emp_car_site_travel.price
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	private Float price;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_site_travel.id
	 * @return  the value of emp_car_site_travel.id
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_site_travel.id
	 * @param id  the value for emp_car_site_travel.id
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_site_travel.gmt_create
	 * @return  the value of emp_car_site_travel.gmt_create
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_site_travel.gmt_create
	 * @param gmtCreate  the value for emp_car_site_travel.gmt_create
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_site_travel.gmt_modified
	 * @return  the value of emp_car_site_travel.gmt_modified
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_site_travel.gmt_modified
	 * @param gmtModified  the value for emp_car_site_travel.gmt_modified
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_site_travel.creator
	 * @return  the value of emp_car_site_travel.creator
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_site_travel.creator
	 * @param creator  the value for emp_car_site_travel.creator
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_site_travel.modifier
	 * @return  the value of emp_car_site_travel.modifier
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public String getModifier() {
		return modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_site_travel.modifier
	 * @param modifier  the value for emp_car_site_travel.modifier
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_site_travel.is_deleted
	 * @return  the value of emp_car_site_travel.is_deleted
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public String getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_site_travel.is_deleted
	 * @param isDeleted  the value for emp_car_site_travel.is_deleted
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_site_travel.start_point
	 * @return  the value of emp_car_site_travel.start_point
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public String getStartPoint() {
		return startPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_site_travel.start_point
	 * @param startPoint  the value for emp_car_site_travel.start_point
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public void setStartPoint(String startPoint) {
		this.startPoint = startPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_site_travel.end_point
	 * @return  the value of emp_car_site_travel.end_point
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public String getEndPoint() {
		return endPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_site_travel.end_point
	 * @param endPoint  the value for emp_car_site_travel.end_point
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public void setEndPoint(String endPoint) {
		this.endPoint = endPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_site_travel.org_id
	 * @return  the value of emp_car_site_travel.org_id
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_site_travel.org_id
	 * @param orgId  the value for emp_car_site_travel.org_id
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column emp_car_site_travel.price
	 * @return  the value of emp_car_site_travel.price
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column emp_car_site_travel.price
	 * @param price  the value for emp_car_site_travel.price
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	public void setPrice(Float price) {
		this.price = price;
	}
}