package com.jing.emperor.domain.model;

import java.util.Date;

public class EmpCarOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.id
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.gmt_create
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.gmt_modified
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.creator
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.modifier
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.is_deleted
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private String isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.car_no
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private String carNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.start_time
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.end_time
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.start_point_id
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private String startPointId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.end_point_id
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private String endPointId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.order_customer_count
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private Integer orderCustomerCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.actual_customer_count
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private Integer actualCustomerCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.total_amount
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private Float totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.actual_amount
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private Float actualAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.status
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_order.org_id
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    private String orgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.id
     *
     * @return the value of emp_car_order.id
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.id
     *
     * @param id the value for emp_car_order.id
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.gmt_create
     *
     * @return the value of emp_car_order.gmt_create
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.gmt_create
     *
     * @param gmtCreate the value for emp_car_order.gmt_create
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.gmt_modified
     *
     * @return the value of emp_car_order.gmt_modified
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.gmt_modified
     *
     * @param gmtModified the value for emp_car_order.gmt_modified
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.creator
     *
     * @return the value of emp_car_order.creator
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.creator
     *
     * @param creator the value for emp_car_order.creator
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.modifier
     *
     * @return the value of emp_car_order.modifier
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.modifier
     *
     * @param modifier the value for emp_car_order.modifier
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.is_deleted
     *
     * @return the value of emp_car_order.is_deleted
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.is_deleted
     *
     * @param isDeleted the value for emp_car_order.is_deleted
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.car_no
     *
     * @return the value of emp_car_order.car_no
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public String getCarNo() {
        return carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.car_no
     *
     * @param carNo the value for emp_car_order.car_no
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setCarNo(String carNo) {
        this.carNo = carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.start_time
     *
     * @return the value of emp_car_order.start_time
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.start_time
     *
     * @param startTime the value for emp_car_order.start_time
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.end_time
     *
     * @return the value of emp_car_order.end_time
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.end_time
     *
     * @param endTime the value for emp_car_order.end_time
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.start_point_id
     *
     * @return the value of emp_car_order.start_point_id
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public String getStartPointId() {
        return startPointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.start_point_id
     *
     * @param startPointId the value for emp_car_order.start_point_id
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setStartPointId(String startPointId) {
        this.startPointId = startPointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.end_point_id
     *
     * @return the value of emp_car_order.end_point_id
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public String getEndPointId() {
        return endPointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.end_point_id
     *
     * @param endPointId the value for emp_car_order.end_point_id
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setEndPointId(String endPointId) {
        this.endPointId = endPointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.order_customer_count
     *
     * @return the value of emp_car_order.order_customer_count
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public Integer getOrderCustomerCount() {
        return orderCustomerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.order_customer_count
     *
     * @param orderCustomerCount the value for emp_car_order.order_customer_count
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setOrderCustomerCount(Integer orderCustomerCount) {
        this.orderCustomerCount = orderCustomerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.actual_customer_count
     *
     * @return the value of emp_car_order.actual_customer_count
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public Integer getActualCustomerCount() {
        return actualCustomerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.actual_customer_count
     *
     * @param actualCustomerCount the value for emp_car_order.actual_customer_count
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setActualCustomerCount(Integer actualCustomerCount) {
        this.actualCustomerCount = actualCustomerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.total_amount
     *
     * @return the value of emp_car_order.total_amount
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public Float getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.total_amount
     *
     * @param totalAmount the value for emp_car_order.total_amount
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setTotalAmount(Float totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.actual_amount
     *
     * @return the value of emp_car_order.actual_amount
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public Float getActualAmount() {
        return actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.actual_amount
     *
     * @param actualAmount the value for emp_car_order.actual_amount
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setActualAmount(Float actualAmount) {
        this.actualAmount = actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.status
     *
     * @return the value of emp_car_order.status
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.status
     *
     * @param status the value for emp_car_order.status
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_order.org_id
     *
     * @return the value of emp_car_order.org_id
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_order.org_id
     *
     * @param orgId the value for emp_car_order.org_id
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }
}