package com.jing.emperor.domain.model;

import java.util.Date;

public class EmpCarSite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_site.id
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_site.gmt_create
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_site.gmt_modified
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_site.creator
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_site.modifier
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_site.is_deleted
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    private String isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_site.org_id
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_car_site.name
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_site.id
     *
     * @return the value of emp_car_site.id
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_site.id
     *
     * @param id the value for emp_car_site.id
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_site.gmt_create
     *
     * @return the value of emp_car_site.gmt_create
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_site.gmt_create
     *
     * @param gmtCreate the value for emp_car_site.gmt_create
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_site.gmt_modified
     *
     * @return the value of emp_car_site.gmt_modified
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_site.gmt_modified
     *
     * @param gmtModified the value for emp_car_site.gmt_modified
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_site.creator
     *
     * @return the value of emp_car_site.creator
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_site.creator
     *
     * @param creator the value for emp_car_site.creator
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_site.modifier
     *
     * @return the value of emp_car_site.modifier
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_site.modifier
     *
     * @param modifier the value for emp_car_site.modifier
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_site.is_deleted
     *
     * @return the value of emp_car_site.is_deleted
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_site.is_deleted
     *
     * @param isDeleted the value for emp_car_site.is_deleted
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_site.org_id
     *
     * @return the value of emp_car_site.org_id
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_site.org_id
     *
     * @param orgId the value for emp_car_site.org_id
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_car_site.name
     *
     * @return the value of emp_car_site.name
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_car_site.name
     *
     * @param name the value for emp_car_site.name
     *
     * @mbg.generated Sat May 06 14:57:05 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}