package com.jing.emperor.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.jing.emperor.domain.model.EmpCarUser;
import com.jing.emperor.domain.model.EmpCarUserExample;

public interface EmpCarUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_user
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	long countByExample(EmpCarUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_user
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_user
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	int insert(EmpCarUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_user
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	int insertSelective(EmpCarUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_user
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	List<EmpCarUser> selectByExample(EmpCarUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_user
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	EmpCarUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_user
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	int updateByExampleSelective(@Param("record") EmpCarUser record, @Param("example") EmpCarUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_user
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	int updateByExample(@Param("record") EmpCarUser record, @Param("example") EmpCarUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_user
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	int updateByPrimaryKeySelective(EmpCarUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_user
	 * @mbg.generated  Mon May 01 14:38:08 CST 2017
	 */
	int updateByPrimaryKey(EmpCarUser record);
}