package com.jing.emperor.domain.mapper;

import com.jing.emperor.domain.model.EmpCarSiteTravel;
import com.jing.emperor.domain.model.EmpCarSiteTravelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpCarSiteTravelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_site_travel
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	long countByExample(EmpCarSiteTravelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_site_travel
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_site_travel
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	int insert(EmpCarSiteTravel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_site_travel
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	int insertSelective(EmpCarSiteTravel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_site_travel
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	List<EmpCarSiteTravel> selectByExample(EmpCarSiteTravelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_site_travel
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	EmpCarSiteTravel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_site_travel
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	int updateByExampleSelective(@Param("record") EmpCarSiteTravel record,
			@Param("example") EmpCarSiteTravelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_site_travel
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	int updateByExample(@Param("record") EmpCarSiteTravel record, @Param("example") EmpCarSiteTravelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_site_travel
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	int updateByPrimaryKeySelective(EmpCarSiteTravel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table emp_car_site_travel
	 * @mbg.generated  Sat May 06 13:45:05 CST 2017
	 */
	int updateByPrimaryKey(EmpCarSiteTravel record);
}