package com.jing.emperor.domain.mapper;

import com.jing.emperor.domain.model.EmpCarOrderDetail;
import com.jing.emperor.domain.model.EmpCarOrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpCarOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order_detail
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    long countByExample(EmpCarOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order_detail
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order_detail
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    int insert(EmpCarOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order_detail
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    int insertSelective(EmpCarOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order_detail
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    List<EmpCarOrderDetail> selectByExample(EmpCarOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order_detail
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    EmpCarOrderDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order_detail
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") EmpCarOrderDetail record, @Param("example") EmpCarOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order_detail
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    int updateByExample(@Param("record") EmpCarOrderDetail record, @Param("example") EmpCarOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order_detail
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    int updateByPrimaryKeySelective(EmpCarOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order_detail
     *
     * @mbg.generated Tue May 02 22:30:57 CST 2017
     */
    int updateByPrimaryKey(EmpCarOrderDetail record);
}