package com.jing.emperor.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.jing.emperor.domain.model.EmpCarOrder;
import com.jing.emperor.domain.model.EmpCarOrderExample;

public interface EmpCarOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    long countByExample(EmpCarOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    int insert(EmpCarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    int insertSelective(EmpCarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    List<EmpCarOrder> selectByExample(EmpCarOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    EmpCarOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") EmpCarOrder record, @Param("example") EmpCarOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    int updateByExample(@Param("record") EmpCarOrder record, @Param("example") EmpCarOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    int updateByPrimaryKeySelective(EmpCarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_car_order
     *
     * @mbg.generated Mon May 01 20:44:02 CST 2017
     */
    int updateByPrimaryKey(EmpCarOrder record);
}